stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t web-application:latest .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push web-application:latest

test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying to EKS..."
    - kubectl apply -f kubernetes/